version: '3.7'

services:
  slinker:
    image: slinker:latest
    container_name: "slinker"
    build:
      context: .
      dockerfile: build/app/Dockerfile
    ports:
      - "8080:8080"
    depends_on: 
      - redis 

  redis:
    image: "redis:latest"
    container_name: "redis"
    command: redis-server 
    ports:
      - "6379:6379"
    environment: 
      - REDIS_REPLICATION_MODE=master

